name:
  "VOC"
class_number:
  21
training:
  #you and add your task as task_3 and so on
  task_1:
    training_type:
      "overlapped"
    design:
      "18-2"
    index_order:
      "default"
    ignore_index:
      [0]
  task_2:
    training_type:
      "overlapped"
    design:
      "3-2-15"
    index_order:
      "default"
    ignore_index:
      [0]
evaluate:
  task_1:
    type:
      ["only stage","all"]
dataset_setting:
  root:
    "PascalVOC12"
  classes:
    "default"
  need_index_name:
    True
increment_setting:
  increment_dataset_name:
    "default"
  split_dataset_name:
    "default"
  #default is name.Segmentation
  split_config:
    "default"
  overlap:
    True
  masking:
    True
  data_masking:
    "current"
  #current or current+old or all
  no_memory:
    True
  save_stage_image_path:
    "default"